######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 31 18:46:20 2014
######################################################################

TEMPLATE = app
TARGET = test.exe
DEPENDPATH += . sigslot
INCLUDEPATH += . sigslot
CONFIG -= qt
QMAKE_CLEAN += $(TARGET) $(QMAKE_TARGET)
QMAKE_CXXFLAGS += -std=c++0x

# Input
HEADERS += sigslot/sigslot.h
SOURCES += test.cc
